"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf.internal import enum_type_wrapper as _enum_type_wrapper
import builtins as _builtins
import sys
import typing as _typing

if sys.version_info >= (3, 11):
    from typing import TypeAlias as _TypeAlias, Never as _Never
else:
    from typing_extensions import TypeAlias as _TypeAlias, Never as _Never

DESCRIPTOR: _descriptor.FileDescriptor

class _StatusType:
    ValueType = _typing.NewType("ValueType", _builtins.int)
    V: _TypeAlias = ValueType  # noqa: Y015

class _StatusTypeEnumTypeWrapper(_enum_type_wrapper._EnumTypeWrapper[_StatusType.ValueType], _builtins.type):
    DESCRIPTOR: _descriptor.EnumDescriptor
    STATUS_TYPE_UNSPECIFIED: _StatusType.ValueType  # 0
    """未指定"""
    STATUS_TYPE_OK: _StatusType.ValueType  # 1
    """成功"""
    STATUS_TYPE_FAILED: _StatusType.ValueType  # 2
    """失敗"""
    STATUS_TYPE_TIMEOUT: _StatusType.ValueType  # 3
    """超時"""
    STATUS_TYPE_CANCELLED: _StatusType.ValueType  # 4
    """取消或拒絕"""

class StatusType(_StatusType, metaclass=_StatusTypeEnumTypeWrapper): ...

STATUS_TYPE_UNSPECIFIED: StatusType.ValueType  # 0
"""未指定"""
STATUS_TYPE_OK: StatusType.ValueType  # 1
"""成功"""
STATUS_TYPE_FAILED: StatusType.ValueType  # 2
"""失敗"""
STATUS_TYPE_TIMEOUT: StatusType.ValueType  # 3
"""超時"""
STATUS_TYPE_CANCELLED: StatusType.ValueType  # 4
"""取消或拒絕"""
Global___StatusType: _TypeAlias = StatusType  # noqa: Y015

@_typing.final
class SmartLockPacket(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    SEQUENCE_FIELD_NUMBER: _builtins.int
    STM32_MESSAGE_FIELD_NUMBER: _builtins.int
    PI_MESSAGE_FIELD_NUMBER: _builtins.int
    sequence: _builtins.int
    @_builtins.property
    def stm32_message(self) -> Global___Stm32Message: ...
    @_builtins.property
    def pi_message(self) -> Global___PiMessage: ...
    def __init__(
        self,
        *,
        sequence: _builtins.int = ...,
        stm32_message: Global___Stm32Message | None = ...,
        pi_message: Global___PiMessage | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["packet_body", b"packet_body", "pi_message", b"pi_message", "stm32_message", b"stm32_message"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["packet_body", b"packet_body", "pi_message", b"pi_message", "sequence", b"sequence", "stm32_message", b"stm32_message"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    _WhichOneofReturnType_packet_body: _TypeAlias = _typing.Literal["stm32_message", "pi_message"]  # noqa: Y015
    _WhichOneofArgType_packet_body: _TypeAlias = _typing.Literal["packet_body", b"packet_body"]  # noqa: Y015
    def WhichOneof(self, oneof_group: _WhichOneofArgType_packet_body) -> _WhichOneofReturnType_packet_body | None: ...

Global___SmartLockPacket: _TypeAlias = SmartLockPacket  # noqa: Y015

@_typing.final
class Stm32Message(_message.Message):
    """============================================================================
    角色專屬包裹訊息
    ============================================================================
    """

    DESCRIPTOR: _descriptor.Descriptor

    PIN_INPUT_FIELD_NUMBER: _builtins.int
    RFID_SCANNED_FIELD_NUMBER: _builtins.int
    RFID_REGISTRATION_FIELD_NUMBER: _builtins.int
    FACE_REGISTRATION_FIELD_NUMBER: _builtins.int
    IR_TRIGGERED_FIELD_NUMBER: _builtins.int
    SYSTEM_RESET_FIELD_NUMBER: _builtins.int
    STATUS_RESPONSE_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def pin_input(self) -> Global___PINInputEvent: ...
    @_builtins.property
    def rfid_scanned(self) -> Global___RfidScannedEvent: ...
    @_builtins.property
    def rfid_registration(self) -> Global___RfidRegistrationEvent: ...
    @_builtins.property
    def face_registration(self) -> Global___FaceRegistrationEvent: ...
    @_builtins.property
    def ir_triggered(self) -> Global___IrTriggeredEvent: ...
    @_builtins.property
    def system_reset(self) -> Global___SystemResetEvent: ...
    @_builtins.property
    def status_response(self) -> Global___StatusResponse: ...
    def __init__(
        self,
        *,
        pin_input: Global___PINInputEvent | None = ...,
        rfid_scanned: Global___RfidScannedEvent | None = ...,
        rfid_registration: Global___RfidRegistrationEvent | None = ...,
        face_registration: Global___FaceRegistrationEvent | None = ...,
        ir_triggered: Global___IrTriggeredEvent | None = ...,
        system_reset: Global___SystemResetEvent | None = ...,
        status_response: Global___StatusResponse | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["body", b"body", "face_registration", b"face_registration", "ir_triggered", b"ir_triggered", "pin_input", b"pin_input", "rfid_registration", b"rfid_registration", "rfid_scanned", b"rfid_scanned", "status_response", b"status_response", "system_reset", b"system_reset"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["body", b"body", "face_registration", b"face_registration", "ir_triggered", b"ir_triggered", "pin_input", b"pin_input", "rfid_registration", b"rfid_registration", "rfid_scanned", b"rfid_scanned", "status_response", b"status_response", "system_reset", b"system_reset"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    _WhichOneofReturnType_body: _TypeAlias = _typing.Literal["pin_input", "rfid_scanned", "rfid_registration", "face_registration", "ir_triggered", "system_reset", "status_response"]  # noqa: Y015
    _WhichOneofArgType_body: _TypeAlias = _typing.Literal["body", b"body"]  # noqa: Y015
    def WhichOneof(self, oneof_group: _WhichOneofArgType_body) -> _WhichOneofReturnType_body | None: ...

Global___Stm32Message: _TypeAlias = Stm32Message  # noqa: Y015

@_typing.final
class PiMessage(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    UNLOCK_FIELD_NUMBER: _builtins.int
    CONTROL_RGB_LED_FIELD_NUMBER: _builtins.int
    STATUS_RESPONSE_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def unlock(self) -> Global___UnlockCommand: ...
    @_builtins.property
    def control_rgb_led(self) -> Global___ControlRgbLedCommand: ...
    @_builtins.property
    def status_response(self) -> Global___StatusResponse: ...
    def __init__(
        self,
        *,
        unlock: Global___UnlockCommand | None = ...,
        control_rgb_led: Global___ControlRgbLedCommand | None = ...,
        status_response: Global___StatusResponse | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["body", b"body", "control_rgb_led", b"control_rgb_led", "status_response", b"status_response", "unlock", b"unlock"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["body", b"body", "control_rgb_led", b"control_rgb_led", "status_response", b"status_response", "unlock", b"unlock"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    _WhichOneofReturnType_body: _TypeAlias = _typing.Literal["unlock", "control_rgb_led", "status_response"]  # noqa: Y015
    _WhichOneofArgType_body: _TypeAlias = _typing.Literal["body", b"body"]  # noqa: Y015
    def WhichOneof(self, oneof_group: _WhichOneofArgType_body) -> _WhichOneofReturnType_body | None: ...

Global___PiMessage: _TypeAlias = PiMessage  # noqa: Y015

@_typing.final
class PINInputEvent(_message.Message):
    """============================================================================
    STM32 事件載荷 (Events)
    ============================================================================
    """

    DESCRIPTOR: _descriptor.Descriptor

    PIN_FIELD_NUMBER: _builtins.int
    pin: _builtins.str
    def __init__(
        self,
        *,
        pin: _builtins.str = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["pin", b"pin"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___PINInputEvent: _TypeAlias = PINInputEvent  # noqa: Y015

@_typing.final
class RfidScannedEvent(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    UID_FIELD_NUMBER: _builtins.int
    uid: _builtins.bytes
    def __init__(
        self,
        *,
        uid: _builtins.bytes = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["uid", b"uid"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___RfidScannedEvent: _TypeAlias = RfidScannedEvent  # noqa: Y015

@_typing.final
class RfidRegistrationEvent(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    UID_FIELD_NUMBER: _builtins.int
    uid: _builtins.bytes
    def __init__(
        self,
        *,
        uid: _builtins.bytes = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["uid", b"uid"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___RfidRegistrationEvent: _TypeAlias = RfidRegistrationEvent  # noqa: Y015

@_typing.final
class FaceRegistrationEvent(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___FaceRegistrationEvent: _TypeAlias = FaceRegistrationEvent  # noqa: Y015

@_typing.final
class IrTriggeredEvent(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___IrTriggeredEvent: _TypeAlias = IrTriggeredEvent  # noqa: Y015

@_typing.final
class SystemResetEvent(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___SystemResetEvent: _TypeAlias = SystemResetEvent  # noqa: Y015

@_typing.final
class UnlockCommand(_message.Message):
    """============================================================================
    樹莓派主動指令 (Commands)
    ============================================================================
    """

    DESCRIPTOR: _descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___UnlockCommand: _TypeAlias = UnlockCommand  # noqa: Y015

@_typing.final
class ControlRgbLedCommand(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    RED_FIELD_NUMBER: _builtins.int
    GREEN_FIELD_NUMBER: _builtins.int
    BLUE_FIELD_NUMBER: _builtins.int
    red: _builtins.bool
    green: _builtins.bool
    blue: _builtins.bool
    def __init__(
        self,
        *,
        red: _builtins.bool = ...,
        green: _builtins.bool = ...,
        blue: _builtins.bool = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["blue", b"blue", "green", b"green", "red", b"red"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___ControlRgbLedCommand: _TypeAlias = ControlRgbLedCommand  # noqa: Y015

@_typing.final
class StatusResponse(_message.Message):
    """============================================================================
    雙向回應載荷 (Responses)
    ============================================================================
    """

    DESCRIPTOR: _descriptor.Descriptor

    STATUS_FIELD_NUMBER: _builtins.int
    MESSAGE_FIELD_NUMBER: _builtins.int
    status: Global___StatusType.ValueType
    message: _builtins.str
    def __init__(
        self,
        *,
        status: Global___StatusType.ValueType = ...,
        message: _builtins.str = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["message", b"message", "status", b"status"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___StatusResponse: _TypeAlias = StatusResponse  # noqa: Y015
